### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by fanatid** [crypto-browserify/ripemd160#15]
Name `ripemd160.js` would more suitable than `ripemd160`. We could use `ripemd160` for node and pure js, like [createHash](https://github.com/crypto-browserify/createHash/).
Thoughts?

**Comment by jprichardson** [comment]
This feels like bikeshedding. I think `ripemd160` is fine and don't see why we would change it to `ripemd160.js`.

**Comment by dcousens** [comment]
NACK
