### ISSUE TITLE
please add a license file

### ISSUE THREAD

**Issue by stocks29** [crypto-browserify/ripemd160#16]
please add a license file. even though it's listed as MIT, a license file makes things a bit easier for consumers :)

**Comment by dcousens** [comment]
Added in https://github.com/crypto-browserify/ripemd160/commit/612b7fcc3bf77e1a882db382d10af5df441d48c9

**Comment by dcousens** [comment]
Ping @jprichardson to confirm

**Comment by jprichardson** [comment]
LGTM
