### ISSUE TITLE
Push hash-base upgrades to npm

### ISSUE THREAD

**Issue by jcalfee** [crypto-browserify/ripemd160#19]
hash-base has released a number of new patches .. for example:
- Reset the digest
- Adds safe-buffer
- Node v4+

https://github.com/crypto-browserify/hash-base/commits/master

I see you have already upgraded hash-base from ^2 to ^3 in HEAD, but that has not been pushed to npm yet..

Is just a simple thing to release and can you push that update please?

**Comment by calvinmetcalf** [comment]
@dcousens is this a major or minor update ?

**Comment by fanatid** [comment]
@calvinmetcalf I think major, because default encoding was changed
https://github.com/crypto-browserify/hash-base/commit/5d95d75d68483c99909b53007110ef6f8509c830
(but prefer wait @dcousens answer)

**Comment by dcousens** [comment]
Am I missing somethign here? `hash-base` is up to date?

**Comment by dcousens** [comment]
In any case,  it is published,  on `npm`.
