### ISSUE TITLE
safe-buffer

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/ripemd160#21]
See for discussion https://github.com/crypto-browserify/ripemd160/pull/20

**Comment by ChALkeR** [comment]
Yeah, `safe-buffer` is already pulled in via a dependency.
```
ripemd160@2.0.1 /home/chalker/repo/ripemd160
├─┬ hash-base@3.0.4
│ ├── inherits@2.0.3
│ └── safe-buffer@5.1.1
└── inherits@2.0.3
```

So this would increase the dependency tree size only in case if versions become desynchronized (I have seen packages effectlively depending on more than one `safe-buffer` versions), and should be unharmful.

Also note that supported Node.js versions do seem inconsistent.
`hash-base@3.0.4` has `"node": ">=4"` in `engines`, so it's strange that `ripemd160` is tested on 0.10.
